before_install:
  - sudo rm -f /etc/mavenrc
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"
jdk:
 - oraclejdk8
cache:
  directories:
    - "$HOME/.m2"
services:
  - docker
install:
  - curl -o $HOME/.m2/settings.xml $SETTINGS_XML_URL
language: java
sudo: required
script:
  - mvn clean package
  - make -C docker push APP=$DOCKER_NAME PROJECT=$DOCKER_REPO
